//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Delivery()
        {
            this.DeliveryLines = new HashSet<DeliveryLine>();
        }
    
        public long deliveryId { get; set; }
        public System.DateTime deliveyDate { get; set; }
        public decimal deliveryPrice { get; set; }
        public string deliveryAddress { get; set; }
        public long userId { get; set; }
        public long cardId { get; set; }
        public string description { get; set; }
    
        public virtual CreditCard CreditCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryLine> DeliveryLines { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
